[2023-12-29T00:10:55.305+0000] {processor.py:161} INFO - Started process (PID=146) to work on /opt/airflow/dags/dags.py
[2023-12-29T00:10:55.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-12-29T00:10:55.475+0000] {logging_mixin.py:188} INFO - [2023-12-29T00:10:55.462+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-12-29T00:10:58.732+0000] {logging_mixin.py:188} INFO - [2023-12-29T00:10:56.954+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 15, in <module>
    createSparkRuntimeConfigurations_Task = PythonOperator(task_id='createSparkRuntimeConfigurations_TaskId',python_callable=createSparkRuntimeConfigurations)
NameError: name 'createSparkRuntimeConfigurations' is not defined
[2023-12-29T00:10:59.020+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-12-29T00:11:09.627+0000] {processor.py:186} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 182, in _run_file_processor
    _handle_dag_file_processing()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 163, in _handle_dag_file_processing
    result: tuple[int, int] = dag_file_processor.process_file(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 843, in process_file
    DagFileProcessor.update_import_errors(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/api_internal/internal_api_call.py", line 114, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 622, in update_import_errors
    existing_import_error_files = [x.filename for x in session.query(errors.ImportError.filename).all()]
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-12-29T21:50:51.650+0000] {processor.py:161} INFO - Started process (PID=89) to work on /opt/airflow/dags/dags.py
[2023-12-29T21:50:51.665+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-12-29T21:50:51.740+0000] {logging_mixin.py:188} INFO - [2023-12-29T21:50:51.738+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-12-29T21:50:52.422+0000] {logging_mixin.py:188} INFO - [2023-12-29T21:50:52.229+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 15, in <module>
    createSparkRuntimeConfigurations_Task = PythonOperator(task_id='createSparkRuntimeConfigurations_TaskId',python_callable=createSparkRuntimeConfigurations)
NameError: name 'createSparkRuntimeConfigurations' is not defined
[2023-12-29T21:50:52.434+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-12-29T21:50:53.030+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags.py took 1.519 seconds
[2023-12-29T21:55:26.731+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/dags.py
[2023-12-29T21:55:26.815+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-12-29T21:55:26.949+0000] {logging_mixin.py:188} INFO - [2023-12-29T21:55:26.930+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-12-29T21:55:28.632+0000] {logging_mixin.py:188} INFO - [2023-12-29T21:55:28.427+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 15, in <module>
    createSparkRuntimeConfigurations_Task = PythonOperator(task_id='createSparkRuntimeConfigurations_TaskId',python_callable=createSparkRuntimeConfigurations)
NameError: name 'createSparkRuntimeConfigurations' is not defined
[2023-12-29T21:55:28.684+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-12-29T21:55:30.631+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags.py took 4.050 seconds
[2023-12-29T21:58:15.835+0000] {processor.py:161} INFO - Started process (PID=149) to work on /opt/airflow/dags/dags.py
[2023-12-29T21:58:15.918+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-12-29T21:58:16.077+0000] {logging_mixin.py:188} INFO - [2023-12-29T21:58:16.075+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-12-29T21:58:16.501+0000] {logging_mixin.py:188} INFO - [2023-12-29T21:58:16.444+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 15, in <module>
    createSparkRuntimeConfigurations_Task = PythonOperator(task_id='createSparkRuntimeConfigurations_TaskId',python_callable=createSparkRuntimeConfigurations)
NameError: name 'createSparkRuntimeConfigurations' is not defined
[2023-12-29T21:58:16.508+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-12-29T21:58:16.927+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags.py took 1.480 seconds
[2023-12-29T21:59:33.536+0000] {processor.py:161} INFO - Started process (PID=196) to work on /opt/airflow/dags/dags.py
[2023-12-29T21:59:33.571+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-12-29T21:59:33.695+0000] {logging_mixin.py:188} INFO - [2023-12-29T21:59:33.693+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-12-29T21:59:34.841+0000] {logging_mixin.py:188} INFO - [2023-12-29T21:59:34.510+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 15, in <module>
    createSparkRuntimeConfigurations_Task = PythonOperator(task_id='createSparkRuntimeConfigurations_TaskId',python_callable=createSparkRuntimeConfigurations)
NameError: name 'createSparkRuntimeConfigurations' is not defined
[2023-12-29T21:59:34.903+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-12-29T21:59:35.548+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags.py took 2.368 seconds
[2023-12-29T22:00:24.132+0000] {processor.py:161} INFO - Started process (PID=240) to work on /opt/airflow/dags/dags.py
[2023-12-29T22:00:24.139+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-12-29T22:00:24.276+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:00:24.274+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-12-29T22:00:24.589+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:00:24.533+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 15, in <module>
    createSparkRuntimeConfigurations_Task = PythonOperator(task_id='createSparkRuntimeConfigurations_TaskId',python_callable=createSparkRuntimeConfigurations)
NameError: name 'createSparkRuntimeConfigurations' is not defined
[2023-12-29T22:00:24.613+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-12-29T22:00:25.073+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags.py took 1.034 seconds
[2023-12-29T22:01:12.000+0000] {processor.py:161} INFO - Started process (PID=282) to work on /opt/airflow/dags/dags.py
[2023-12-29T22:01:12.039+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-12-29T22:01:12.183+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:01:12.181+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-12-29T22:01:12.987+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:01:12.887+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 15, in <module>
    createSparkRuntimeConfigurations_Task = PythonOperator(task_id='createSparkRuntimeConfigurations_TaskId',python_callable=createSparkRuntimeConfigurations)
NameError: name 'createSparkRuntimeConfigurations' is not defined
[2023-12-29T22:01:13.005+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-12-29T22:01:13.478+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags.py took 1.619 seconds
[2023-12-29T22:01:52.918+0000] {processor.py:161} INFO - Started process (PID=313) to work on /opt/airflow/dags/dags.py
[2023-12-29T22:01:52.940+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-12-29T22:01:53.019+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:01:53.017+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-12-29T22:01:53.274+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:01:53.213+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 15, in <module>
    createSparkRuntimeConfigurations_Task = PythonOperator(task_id='createSparkRuntimeConfigurations_TaskId',python_callable=createSparkRuntimeConfigurations)
NameError: name 'createSparkRuntimeConfigurations' is not defined
[2023-12-29T22:01:53.281+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-12-29T22:01:53.667+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags.py took 0.841 seconds
[2023-12-29T22:02:35.803+0000] {processor.py:161} INFO - Started process (PID=348) to work on /opt/airflow/dags/dags.py
[2023-12-29T22:02:35.828+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-12-29T22:02:35.859+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:02:35.857+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-12-29T22:02:36.084+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:02:36.037+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 15, in <module>
    createSparkRuntimeConfigurations_Task = PythonOperator(task_id='createSparkRuntimeConfigurations_TaskId',python_callable=createSparkRuntimeConfigurations)
NameError: name 'createSparkRuntimeConfigurations' is not defined
[2023-12-29T22:02:36.091+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-12-29T22:02:36.604+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags.py took 0.951 seconds
[2023-12-29T22:03:11.749+0000] {processor.py:161} INFO - Started process (PID=378) to work on /opt/airflow/dags/dags.py
[2023-12-29T22:03:11.822+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-12-29T22:03:11.852+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:03:11.850+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-12-29T22:03:12.126+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:03:12.088+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 15, in <module>
    createSparkRuntimeConfigurations_Task = PythonOperator(task_id='createSparkRuntimeConfigurations_TaskId',python_callable=createSparkRuntimeConfigurations)
NameError: name 'createSparkRuntimeConfigurations' is not defined
[2023-12-29T22:03:12.133+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-12-29T22:03:12.479+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags.py took 0.788 seconds
[2023-12-29T22:04:03.115+0000] {processor.py:161} INFO - Started process (PID=420) to work on /opt/airflow/dags/dags.py
[2023-12-29T22:04:03.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-12-29T22:04:03.182+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:04:03.180+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-12-29T22:04:03.465+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:04:03.427+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 15, in <module>
    createSparkRuntimeConfigurations_Task = PythonOperator(task_id='createSparkRuntimeConfigurations_TaskId',python_callable=createSparkRuntimeConfigurations)
NameError: name 'createSparkRuntimeConfigurations' is not defined
[2023-12-29T22:04:03.475+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-12-29T22:04:03.915+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags.py took 0.907 seconds
[2023-12-29T22:28:32.105+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/dags/dags.py
[2023-12-29T22:28:32.115+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-12-29T22:28:32.156+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:28:32.152+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-12-29T22:28:33.193+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:28:33.088+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 15, in <module>
    createSparkRuntimeConfigurations_Task = PythonOperator(task_id='createSparkRuntimeConfigurations_TaskId',python_callable=createSparkRuntimeConfigurations)
NameError: name 'createSparkRuntimeConfigurations' is not defined
[2023-12-29T22:28:33.217+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-12-29T22:28:34.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags.py took 2.846 seconds
[2023-12-29T22:31:26.627+0000] {processor.py:161} INFO - Started process (PID=144) to work on /opt/airflow/dags/dags.py
[2023-12-29T22:31:26.699+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-12-29T22:31:26.956+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:31:26.954+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-12-29T22:31:27.386+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:31:27.334+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 15, in <module>
    createSparkRuntimeConfigurations_Task = PythonOperator(task_id='createSparkRuntimeConfigurations_TaskId',python_callable=createSparkRuntimeConfigurations)
NameError: name 'createSparkRuntimeConfigurations' is not defined
[2023-12-29T22:31:27.404+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-12-29T22:31:27.719+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags.py took 1.157 seconds
[2023-12-29T22:33:14.437+0000] {processor.py:161} INFO - Started process (PID=200) to work on /opt/airflow/dags/dags.py
[2023-12-29T22:33:14.452+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-12-29T22:33:14.478+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:33:14.476+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-12-29T22:33:14.935+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:33:14.749+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 15, in <module>
    createSparkRuntimeConfigurations_Task = PythonOperator(task_id='createSparkRuntimeConfigurations_TaskId',python_callable=createSparkRuntimeConfigurations)
NameError: name 'createSparkRuntimeConfigurations' is not defined
[2023-12-29T22:33:14.986+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-12-29T22:33:15.522+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags.py took 1.185 seconds
[2023-12-29T22:34:15.716+0000] {processor.py:161} INFO - Started process (PID=246) to work on /opt/airflow/dags/dags.py
[2023-12-29T22:34:15.810+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-12-29T22:34:16.096+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:34:16.064+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-12-29T22:34:17.859+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:34:17.726+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 15, in <module>
    createSparkRuntimeConfigurations_Task = PythonOperator(task_id='createSparkRuntimeConfigurations_TaskId',python_callable=createSparkRuntimeConfigurations)
NameError: name 'createSparkRuntimeConfigurations' is not defined
[2023-12-29T22:34:17.903+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-12-29T22:34:18.709+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags.py took 3.262 seconds
[2023-12-29T22:35:45.587+0000] {processor.py:161} INFO - Started process (PID=292) to work on /opt/airflow/dags/dags.py
[2023-12-29T22:35:45.613+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-12-29T22:35:45.690+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:35:45.661+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-12-29T22:35:45.976+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:35:45.921+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 15, in <module>
    createSparkRuntimeConfigurations_Task = PythonOperator(task_id='createSparkRuntimeConfigurations_TaskId',python_callable=createSparkRuntimeConfigurations)
NameError: name 'createSparkRuntimeConfigurations' is not defined
[2023-12-29T22:35:45.999+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-12-29T22:35:46.380+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags.py took 0.916 seconds
[2023-12-29T22:38:04.244+0000] {processor.py:161} INFO - Started process (PID=350) to work on /opt/airflow/dags/dags.py
[2023-12-29T22:38:04.279+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-12-29T22:38:04.315+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:38:04.312+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-12-29T22:38:04.798+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:38:04.697+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 15, in <module>
    createSparkRuntimeConfigurations_Task = PythonOperator(task_id='createSparkRuntimeConfigurations_TaskId',python_callable=createSparkRuntimeConfigurations)
NameError: name 'createSparkRuntimeConfigurations' is not defined
[2023-12-29T22:38:04.806+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-12-29T22:38:05.421+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags.py took 1.295 seconds
[2023-12-29T22:57:04.029+0000] {processor.py:161} INFO - Started process (PID=432) to work on /opt/airflow/dags/dags.py
[2023-12-29T22:57:04.051+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dags.py for tasks to queue
[2023-12-29T22:57:04.315+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:57:04.197+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dags.py
[2023-12-29T22:57:05.614+0000] {logging_mixin.py:188} INFO - [2023-12-29T22:57:05.501+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/dags.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dags.py", line 15, in <module>
    createSparkRuntimeConfigurations_Task = PythonOperator(task_id='createSparkRuntimeConfigurations_TaskId',python_callable=createSparkRuntimeConfigurations)
NameError: name 'createSparkRuntimeConfigurations' is not defined
[2023-12-29T22:57:05.631+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dags.py
[2023-12-29T22:57:06.442+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dags.py took 2.434 seconds
